export { default as TestPositive } from './TestPositive';
export { default as LatestOrders } from './LatestOrders';
export { default as LatestProducts } from './LatestProducts';
export { default as AbsoluteCases } from './AbsoluteCases';
export { default as IncreasedCases } from './IncreasedCases';
export { default as DeathRate } from './DeathRate';
export { default as Total} from './Total';
export { default as Hospitalized } from './Hospitalized';
export { default as UsersByDevice } from './UsersByDevice';
export { default as SimpleSelect } from './Sortbystate';
